#XArm的初始端执行器位置和方向
#格式：[x， y, z，roll，pitch，yaw]
#单位：毫米和弧度
eff_position: [223.778564, 0.357308, 285.864502, -0.390661, 1.521898, -0.379501]

#从pika夹爪中心坐标系到XArm末端执行器坐标系的转换
#格式：[x， y, z, roll，pitch，yaw]
#单位：米和弧度
pika_to_arm: [0, 0, 0, 0, 1.570796, 0]

